### ISSUE TITLE
V3.7 checklist

### ISSUE THREAD

**Issue by jhoopes** [jhoopes/moodle-mod_activequiz#31]
- [ ] Get #28 fixed and implemented
- [ ] Work with Davo to integrate #30 
- [ ] Ensure that newer "under the hood" features are complete
* Moving to separate renderers
* Report architecture is in place and doesn't break the default "Overview" report
- [ ] Updates to documentation in the readme, the plugin page, and Moodle.org
